### ISSUE TITLE
RsRedisConnectionPoolTest Pharo 10 blocks

### ISSUE THREAD

**Issue by sebastianconcept** [mumez/RediStick#29]
I'm currently using RediStick as a dependency for https://sebastianconcept.github.io/Mapless/ and I'd very much like to continue using it to leverage some Mapless features.

RediStick loads and all basic tests pass but from Pharo 10 the `RsRedisConnectionPoolTest` tests gets  blocked. I didn't have a chance to look further yet but wanted to register here at this time.

**Comment by mumez** [comment]
Thanks for the report. I've tried the connection pool test, but the test was (luckily) green.
I've tested it with Pharo 11 on Windows. Could you give me more specific info? The test takes some time because of the high load, so it may fail on some platforms.

![2024-01-31 17_24_17-C__Users_ume_Documents_Pharo_images_Pharo11-redistick_Pharo11-redistick image](https://github.com/mumez/RediStick/assets/705350/90520b22-7440-4f70-b993-deec1afd3981)

**Comment by sebastianconcept** [comment]
Tested that in macOS but I'm confused now because it passed all after loading it in a fresh Pharo 11. 

Closing as false positive. If I can reproduce it or know more I'll reopen, no worries.

And thank you for the quick response and checking
